post-detail에서 develop 브랜치로 풀리퀘 보내용
LikeLion-at-CAU-10th/Palette-React pull request #5
Opened 2022-08-03 16:26 UTC by harin0707

2022-08-05 07:06 UTC, yunseonyeong requested changes

2022-08-05 07:06 UTC, yunseonyeong commented on src/component/DarkModeToggle.js
> +                <ToggleBall onClick={toggleDarkMode}/>
onClick 이벤트를 ToggleBall 에 넣는 것보다 ToggleButton 전체에 넣는게 더 조작하기 편할 것 같아요

2022-08-05 07:06 UTC, yunseonyeong commented on src/styles/PDstyled.js
> +export const PostContents =styled.div`
PostContents 의 글 내용이 많아지면 튀어나오지 않고 스크롤이 생기도록 styling 해주세요

2022-08-05 07:06 UTC, yunseonyeong commented on src/component/PostDetailProps.js
> +                        <EditButton> 수정 </EditButton>
삭제 버튼 클릭 시, 삭제 확인 모달도 만들어서 노출되도록 구현해주세요 !

2022-08-05 07:06 UTC, yunseonyeong commented on src/component/PostDetailProps.js
> +            <PostContents>{post.contents}</PostContents>
post.contents 자간과 줄 간격도 조절해주세요

2022-08-16 18:59 UTC, closed without merging

2022-08-16 19:00 UTC, Haeyoon-Cho commented
branch 이동 (post-detail >> post)